server:
  port: 8081

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:semi;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

    # enable H2 web console and set url for web console
    h2:
      console:
        enabled: true
        path: /h2-console

    jpa:
      hibernate:
        ddl-auto: create-drop
        use-new-id-generator-mappings: false
      generate-ddl: false

      properties:
        hibernate:
          show_sql: true # SQL 표시
          format_sql: true # SQL 포맷팅
          use_sql_comments: true # 주석 표시

logging:
  level:
    root: warn
    com.sat.study: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # 값 매핑